build-container-blunders:
	docker build --tag=322456/broken_bulb:dev ./broken_bulb
	docker build --tag=322456/faulty_roger:dev ./faulty_roger
	docker build --tag=322456/smoked_server:dev ./smoked_server

push-container-blunders:
	docker push 322456/broken_bulb:dev
	docker push 322456/faulty_roger:dev
	docker push 322456/smoked_server:dev